name: Playwright Tests
permissions:
  contents: write
on:
  schedule:
    - cron: '00 8 * * 0,2,4,6'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_APP_ID: ${{ secrets.REDDIT_APP_ID }}
      REDDIT_APP_SECRET: ${{ secrets.REDDIT_APP_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: ðŸšš Install Dependencies
      run: npm ci
    - name: ðŸŽ­ Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: ðŸ§ª Run Playwright tests
      run: npx playwright test
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - name: ðŸŽ¹ Add Audio
      run: ffmpeg -i canvas-made.webm -i assets/bgm.mp3 -map 0:v -map 1:a -c:v copy -shortest output.webm
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
        retention-days: 1
    - name: ðŸ“¼ Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_id }}
        name: Meme Comp | Barcode:${{ github.run_id }}
        files: |
          output.webm
